name: Discord Commit Notification
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        args: 'MESSAGE INCOMING... {{ GITHUB_ACTION }} SAYS... The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed. ...I showed you my commit. Please respond.'
